
@baseUrl =http://localhost:3000
@authorization = Bearer {{login.response.body.access_token}}


### REGISTER
# @name register
POST {{baseUrl}}/auth/register
Accept: application/json
Content-Type: application/json

{
    "email": "juan2@geekshubs.om",
    "password": "qwerty:A12",
    "username":"garn2"
}



### LOGIN
# @name login
POST {{baseUrl}}/auth/login
Accept: application/json
Content-Type: application/json

{
    "email": "EMIAL@EMAIL.COM",
    "password": "PASS",
    "remember_me": false
}


###  Albaran id
GET {{baseUrl}}/albaran/4/centro/2
Accept: application/json
Authorization: {{authorization}}
